### ISSUE TITLE
Package is incompatible with Flutter! collection ^1.17.0 is not supported yet

### ISSUE THREAD

**Issue by ynnob** [jonasroussel/dart_jsonwebtoken#29]
**Problem:**
Starting with Version 2.5.0 `flutter pub get` will fail because dart_jsonwebtoken >=2.5.0 depends on collection ^1.17.0 but flutter_test from sdk depends on collection 1.16.0

Because dart_jsonwebtoken >=2.5.0 depends on collection ^1.17.0 and every version of flutter from sdk depends on collection 1.16.0, dart_jsonwebtoken >=2.5.0 is incompatible with flutter from sdk.

**Error:**
```
Because every version of flutter_test from sdk depends on collection 1.16.0 and dart_jsonwebtoken >=2.5.0 depends on collection ^1.17.0, flutter_test from sdk is incompatible with dart_jsonwebtoken >=2.5.0.     
So, because helltax depends on both dart_jsonwebtoken ^2.5.0 and flutter_test from sdk, version solving failed.
Running "flutter pub get" in helltax...                                 
pub get failed (1; So, because helltax depends on both dart_jsonwebtoken ^2.5.0 and flutter_test from sdk, version solving failed.)
```

**pubspec.yaml**
```
name: X
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.4

  # Dependecy Injection
  get_it: ^7.2.0

  # Webrequests
  http: ^0.13.5

  # Generate/Decode/Encode JWT
  dart_jsonwebtoken: ^2.5.0

  # Use Cookies
  cookie_jar: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
```
